config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  root to: 'books#index'
  devise_for :users, controllers: { registrations: "registrations" }
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  
  
  resources :books do 
    member do 
      put "add", to: "books#library"
      put "remove", to: "books#library"
    end
  end
  resources :library, only:[:index]
  resources :pricing, only:[:index]
  resources :subscriptions
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  #before_action :authenticate_user!
  #has_one_attached :thumbnail
  
  belongs_to :user
  has_many :libraries
  #has_many :added_books, through: :libraries, source: :user
end

app/models/library.rb
class Library < ApplicationRecord
  belongs_to :book
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  #before_action :set_book, only: [:show, :edit, :update, :destroy, :library]
  #before_action :authenticate_user!, except: [:index, :show]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @book = Book.find(params[:id])
  end

  # GET /books/new
  def new
    @book = Book.new
    #@book = current_user.books.build
  end

  # GET /books/1/edit
  def edit
    @book = Book.find(params[:id])
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)
    @book.user = current_user
    if @book.save
      flash[:success] = "Book has been added"
      redirect_to book_path(@book)
    else
      flash.now[:danger] = "Error! Please try again"
      render 'new'
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:success] = "Book was Updated"
      redirect_to book_path(@book)
    else
      render 'edit'
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    flash[:danger] = "Book has been removed"
    redirect_to books_path
  end

  # Add and remove books to library
  # for current_user
  def library
    type = params[:type]

    if type == "add"
      current_user.library_additions << @book
      redirect_to library_index_path, notice: "#{@book.title} was added to your library"

    elsif type == "remove"
      current_user.library_additions.delete(@book)
      redirect_to root_path, notice: "#{@book.title} was removed from your library"
    else
      # Type missing, nothing happens
      redirect_to book_path(@book), notice: "Looks like nothing happened. Try once more!"
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :description, :author, :thumbnail, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/library_controller.rb
class LibraryController < ApplicationController
end

app/controllers/pricing_controller.rb
class PricingController < ApplicationController
  #layout "subscribe"

  def index
  end
  
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  protected

  def after_sign_up_path_for(resource)
    '/pricing'
  end
  
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  #layout "subscribe"
  before_action :authenticate_user!, except: [:new, :create]


  def new
    if user_signed_in? && current_user.subscribed?
      redirect_to root_path, notice: "You are already a subscriber"
    end
  end

  def create
    Stripe.api_key = Rails.application.credentials.stripe_api_key

    plan_id = params[:plan_id]
    plan = Stripe::Plan.retrieve(plan_id)
    token = params[:stripeToken]

    customer = if current_user.stripe_id?
                Stripe::Customer.retrieve(current_user.stripe_id)
               else
                Stripe::Customer.create(email: current_user.email, source: token)
              end

    subscription = customer.subscriptions.create(plan: plan.id)

    options = {
      stripe_id: customer.id,
      stripe_subscription_id: subscription.id,
      subscribed: true
    }

    options.merge!(
      card_last4: params[:user][:card_last4],
      card_exp_month: params[:user][:card_exp_month],
      card_exp_year: params[:user][:card_exp_year],
      card_type: params[:user][:card_type]
    ) if params[:user][:card_last4]

    current_user.update(options)

    redirect_to root_path, notice: "Your subscription was setup successfully!"
  end

  def destroy
    customer = Stripe::Customer.retrieve(current_user.stripe_id)
    customer.subscriptions.retrieve(current_user.stripe_subscription_id).delete
    current_user.update(stripe_subscription_id: nil)
    current_user.subscribed = false

    redirect_to root_path, notice: "Your subscription has been cancelled."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
      <strong>
       #{pluralize(resource.errors.count, "error")} must be fixed
      </strong>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/library_helper.rb
module LibraryHelper
end

app/views/books/_book-controls.html.erb
<% if subscribed? %>

  <% if user_added_to_library?(current_user, book) %>

    <%= link_to 'Remove from library', add_book_path(book, type: "remove"), method: :put, class: "btn btn-danger btn-lg" %>

    <% if controller.controller_name == "library" %>
      <%= link_to 'Download', '#', class:"btn btn-success btn-lg" %>
    <% end %>

  <% else %>
    <%= link_to 'Add to library', add_book_path(book, type: "add"), method: :put, class: "btn btn-primary btn-lg" %>
  <% end %>

<% else %>
  <%= link_to 'Add to library', new_user_registration_path, class: "btn btn-primary btn-lg" %>
<% end %>

app/views/books/_book.html.erb
<div class="book">
  <div class="card">
    <div class="card-image">
      <figure class="">
        <%#= link_to image_tag(book.thumbnail), book %>
      </figure>
    </div>
    <div class="row">
      <div class="col-md-8 col-md-offset-4">
        <div class="media-content">
          <p class="title is-4"><%= book.title %></p>
          <p class="subtitle is-6"><%= book.author %></p>
        </div>
      </div>

      <div class="row">
         <%# if subscribed? %>

          <%# if user_added_to_library?(current_user, book) %>

            <%#= link_to 'Remove from library', add_book_path(book, type: "remove"), method: :put, class: "btn btn-danger btn-lg" %>

            <%# if controller.controller_name == "library" %>
              <%#= link_to 'Download', '#', class:"btn btn-success btn-lg" %>
            <%# end %>

          <%# else %>
            <%#= link_to 'Add to library', add_book_path(book, type: "add"), method: :put, class: "btn btn-success btn-lg" %>
          <%# end %>

        <%# else %>
          <%#= link_to 'Add to library', new_user_registration_path, class: "btn btn-success btn-lg" %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="row">
    <%# if admin? %>
      <%= link_to 'Edit', edit_book_path(@book), class:"btn btn-primary btn-sm" %>
      <%= link_to 'Delete', book_path(@book), method: :delete, data: { confirm: "Are you sure? "}, class:"btn btn-danger btn-sm" %>
    <%# end %>
  </div>
</div>

app/views/books/_errors.html.erb
<% if @book.errors.any? %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="panel panel-danger">
        <div class="panel-heading">
          <h2 class="panel-title">
            <%= pluralize(@book.errors.count, "error") %> prohibited this <%= @book.class %> from being saved:
          </h2>
        <div class="panel-body">
          <ul>
            <% @book.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/books/_form.html.erb
<div class="row">
  <div class="col-md-12">
          <%= form_for(@book, :html => {class: "form-horizontal", role: "form"}) do |f| %>
          <%= render 'books/errors' %>
           <div class="form-group">
             <div class="control-label col-md-2">
                <%= f.label :title %> 
             </div>
             <div class="col-md-8">
               <%= f.text_field :title, class: 'form-control', placeholder: "Name of Book", autofocus: true %>
             </div>
           </div>
          <div class="form-group">
             <div class="control-label col-md-2">
                <%= f.label :description %> 
             </div>
             <div class="col-md-8">
               <%= f.text_area :description, rows: 5, class: 'form-control', placeholder: "Add Book description" %>
             </div>
           </div>
           <div class="form-group">
             <div class="control-label col-md-2">
                <%= f.label :author %> 
             </div>
             <div class="col-md-8">
               <%= f.text_field :author, class: 'form-control', placeholder: "Name of Author", autofocus: true %>
             </div>
           </div>
          <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
              <%= f.submit class: "btn btn-primary" %> 
              <%#= link_to "Back to Index", todos_path, class: "btn btn-warning" %>
            </div>
          </div>
        <% end %>
      </p>
  </div>
</div>

app/views/books/edit.html.erb
<h2 class="text-center">Add a Book</h2>
<%= render 'books/form'%>

app/views/books/index.html.erb
<section class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="well text-center">
      <h1 class="title">
         Book Delivery
      </h1>
      <h2 class="subtitle">
        Check out some of the latest titles
      </h2>
    </div>
  </div>
</section>

<section class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="text-center">
    <% @books.each do |book| %>
        <div class="well">
          <h2><span>Title: </span><%= book.title %> </h2>
          <p><span><strong>Description:</strong> </span> <%= book.description %></p>
          <h4><span>Author: </span> <%= book.author %></h4>
          <%= link_to "View", book_path(book), class: "btn btn-info "%>
          <%# if logged_in? && current_user == todo.user || current_user.admin? %>
            <%= link_to "Edit", edit_book_path(book), class: "btn btn-warning bttn" %>
            <%= link_to "Delete", book_path(book), method: :delete, data: {confirm: "Are you sure??"}, class: "btn btn-danger bttn" %>
          <%# end %>
        </div>
      <% end %>
  </div>
  </div>
</section>

app/views/books/new.html.erb
<h2 class="text-center">Add a Book</h2>
<%= render 'books/form'%>

app/views/books/show.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
  <!-- <div class="column is-4">
      <%#= image_tag @book.thumbnail.variant(resize: "320x495"), alt: "#{@book.title} by #{@book.author}" %>
    </div> -->
    <div class="well">
      <h1 class="text-center"><%= @book.title %></h1>
      <h4 class="text-center">Author: <%= @book.author %></h4>
        
          <%#= render 'book-controls', book: @book %>
          <p class="text-center d-flex"><%= @book.description %></p>
          <p></p>
          
      

      <%# if admin? %>
        <p class="text-center">
          <%= link_to 'Index',books_path, class: 'btn btn-warning' %> |
          <%= link_to 'Edit', edit_book_path(@book), class: 'btn btn-primary' %> |
          <%= link_to 'Delete', book_path(@book), method: :delete, data: {confirm: "Are you sure??"}, class: "btn btn-danger" %>
        </p>
      <%# end %>
      </div>
    </div>
</div>

app/views/home/index.html.erb
<div class="row">
  <div class="jumbotron">
    <h1 class="text-center">The Library</h1>
  </div>
  <div class="text-center">
    <p><%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary btn-lg" %></p>
  </div>
</div>

app/views/layouts/_flash.html.erb
<% flash.each do |name, msg| %>
	<div class="alert alert-<%= name %>">
			<%= msg %>
	</div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
		<nav>
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<div class="collapse navbar-collapse" id="myNavbar">
				<ul class="nav navbar-nav navbar-left">
					<li><%= link_to "Home", root_path %></li>
					<% if current_user %>
            <li class="nav-name"><%= current_user.email %> <%#= "(Admin Status)" if current_user.admin? %></li>
					<% end %>
				</ul>
				<ul class="nav navbar-nav navbar-right">
					<% if current_user %>
						<li class="nav-buttons"><%= link_to "Add Book", new_book_path, class: "btn btn-primary" %></li>
						<li class="nav-buttons"><%= link_to "Log out", destroy_user_session_path, class: "btn btn-danger", method: :delete %></li>
					<% else %>
					<li class="nav-buttons"><%= link_to "Log in", new_user_session_path, class: "btn btn-primary", method: :get %></li>
					<% end %>
				</ul>
			</div>
		</nav>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookLibrary</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar'%>
    <div class="container">
    <%= render 'layouts/flash'%>
      <%= yield %>
    </div>
  </body>
</html>

app/views/library/index.html.erb
<section class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="text-center well">
      <h1 class="title">
        <i class="fa fa-book"></i> <%#= current_user.name %>'s Library
      </h1>
      <h2 class="subtitle">
        Download or manage your chosen titles below:
      </h2>
    </div>
  </div>
</section>

<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <%# if @library_books.exists? %>
    <div class="book-grid">
      <%#= render @library_books, book: @book %>
    </div>
    <%# else %>
    <article class="message">
      <div class="message-body">You haven't added any books to your library yet. <%#= link_to 'Add some', root_path %>.</div>
    </article>
    <%# end %>
    </div>
</div>

app/views/pricing/index.html.erb
<section class="row">
  <div class="col-md-8 col-md-offset-2 text-center">
    <h1 class="title">Pricing</h1>
    <h2 class="subtitle">Choose the best plan that matches your reading consistency and budget.</h2>
    </div>
    <div class="col-md-6 col-md-offset-4">
      <div class="well">
        <h3 class="text-center">Starter</h3>
        <div class="text-center"><span class="plan-price-amount"><span class="plan-price-currency">£</span>5</span> /month</div>
        <div class="">
          <div class="text-center">5 Downloads</div>
        </div>
        <div class="plan-footer text-center">
          <% if user_signed_in? %>
            <%= link_to 'Subscribe', new_subscription_path(plan: "starter", plan_id: Rails.application.credentials.starter), class:"btn btn-primary btn-lg" %>
          <% else %>
            <%= link_to 'Subscribe', new_user_registration_path, class: 'btn btn-primary btn-lg' %>
         <% end %>
        </div>
      </div>
      <div class="well">
        <h3 class="text-center">Book Worm</h3>
        <div class="text-center"><span class="plan-price-amount"><span class="plan-price-currency">£</span>10</span> /month</div>
        <div class="">
          <div class="text-center">10 Downloads</div>
        </div>
        <div class="plan-footer text-center">
           <% if user_signed_in? %>
            <%= link_to 'Subscribe', new_subscription_path(plan: "book_worm", plan_id: Rails.application.credentials.book_worm), class:"btn btn-primary btn-lg" %>
          <% else %>
            <%= link_to 'Subscribe', new_user_registration_path, class: 'btn btn-primary btn-lg' %>
         <% end %>
        </div>
      </div>
      <div class="well">
        <h3 class="text-center">Scholar</h3>
        <div class="text-center"><span class="plan-price-amount"><span class="plan-price-currency">£</span>30</span> /month</div>
        <div class="plan-items">
          <div class="text-center">30 Downloads</div>
        </div>
        <div class="plan-footer text-center">
         <% if user_signed_in? %>
            <%= link_to 'Subscribe', new_subscription_path(plan: "scholar", plan_id: Rails.application.credentials.scholar), class:"btn btn-primary btn-lg" %>
          <% else %>
            <%= link_to 'Subscribe', new_user_registration_path, class: 'btn btn-primary btn-lg' %>
         <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/subscriptions/new.html.erb
<div class="row">
  <div class="text-center">
    <div class="col-md-6 col-md-offset-2">
      <h1 class="title is-3">Subscribe</h1>
      <hr />
      <p>Chosen plan: <strong><%= params[:plan] %>
      <hr/>
      <%= form_tag subscriptions_path, id: "payment-form" do |form| %>

        <div class="field-form-group">
          <label for="card-element" class="label">Enter credit or debit card</label>

          <div id="card-element">
            <!-- A Stripe element will be intserted here !-->
          </div>

          <div id="card-errors" role="alert"></div>

          <%= hidden_field_tag :plan_id, params[:plan_id] %>

          <button class="button is-fullwidth is-link mt4">Submit</button>
        </div>

      <% end %>
    </div>
  </div>
</div>